for file in ~/.{path,bash_prompt,exports,aliases,functions,extra,hosts}; do
    if [[ -r "$file" ]]; then
        source "$file"
    fi
done
unset file

# yup I don't like vim
export EDITOR=nano
export GIT_EDITOR=nano

if [[ -f $(brew --prefix)/bin/rbenv ]]; then
    eval "$(rbenv init -)"
fi

if [[ -f $(brew --prefix)/share/bash-completion/bash_completion ]]; then
    . $(brew --prefix)/share/bash-completion/bash_completion
fi

[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

# Autocorrect typos in path names when using `cd`
shopt -s cdspell
shopt -s dirspell

# Just type directory without the cd
shopt -s autocd

shopt -s histappend
shopt -s checkwinsize

# Show some colors ls
export CLICOLOR=1
export LSCOLORS=cxfxcxdxbxegedabagacad
export GOPATH=~/.go/
export HISTSIZE=5000000
