for file in ~/.{path,bash_prompt,exports,aliases,functions,extra,hosts}; do
    if [[ -r "$file" ]]; then
        source "$file"
    fi
done
unset file

# yup I don't like vim
export EDITOR=nano
export GIT_EDITOR=nano

# /usr/local/bin before /usr/bin
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/$(whoami)/.dotfiles/bin
if [[ -d "$HOME/.rbenv/" ]]; then
    PATH="$HOME/.rbenv/bin:$PATH"
fi

export PATH
launchctl setenv PATH $PATH

if [[ -f $(brew --prefix)/bin/rbenv ]]; then
    eval "$(rbenv init -)"
fi

export NODE_PATH=$NODE_PATH:/usr/local/lib/node:/usr/local/lib/node_modules

if [[ -f $(brew --prefix)/share/bash-completion/bash_completion ]]; then
    . $(brew --prefix)/share/bash-completion/bash_completion
fi

[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

# Autocorrect typos in path names when using `cd`
shopt -s cdspell
shopt -s dirspell

# Just type directory without the cd
shopt -s autocd

shopt -s histappend
shopt -s checkwinsize

# Show some colors ls
export CLICOLOR=1
export LSCOLORS=cxfxcxdxbxegedabagacad
export GOPATH=~/.go/
