---
  - name: Install brew packages
    homebrew:
      name: "{{ item }}"
      state: latest
    with_items:
      - chromedriver
      - git
      - git-extras
      - htop
      - icdiff
      - jq
      - mtr
      - nano
      - ncdu
      - node
      - packer
      - packer-completion
      - php71
      - php-code-sniffer
      - pngquant
      - python
      - python3
      - rbenv
      - ruby-build
      - selenium-server-standalone
      - tmux
      - tmux-cssh
      - vagrant-completion
      - docker-completion
      - docker-compose-completion
      - docker-machine-completion
      - tree
      - watch
      - wget
