---
  - name: Install from cask
    homebrew_cask:
      name: "{{ item }}"
      state: present
    ignore_errors: yes
    with_items:
      - alfred
      - cleanapp
      - controlplane
      - dropbox
      - google-chrome
      - google-chrome-canary
      - slack
      - skype
      - skype-for-business
      - iterm2
      - istat-menus
      - kobo
      - macdown
      - atom
      - sequel-pro
      - spotify
      - torbrowser
      - vagrant
      - vlc
      - virtualbox
      - phpstorm
      - filezilla
      - lastpass
      - tunnelblick
      - cyberduck
      - osxfuse
      - insomnia
