---
  - name: Check if brew is already installed
    stat:
      path: "/usr/local/bin/brew"
    register: brew_stat

  - name: Install homebrew
    shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    when: brew_stat.stat.exists is defined and brew_stat.stat.exists == False
