for file in ~/.{path,bash_prompt,exports,aliases,extra,hosts}; do
    if [[ -r "$file" ]]; then
        source "$file"
    fi
done
unset file

gcloud_bash_completion="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc"
if [[ -r $gcloud_bash_completion ]]; then
    source $gcloud_bash_completion
fi

# yup I don't like vim
export EDITOR=nano
export GIT_EDITOR=nano

if [[ -f $(brew --prefix)/bin/rbenv ]]; then
    eval "$(rbenv init -)"
fi

if [[ -f $(brew --prefix)/share/bash-completion/bash_completion ]]; then
    . $(brew --prefix)/share/bash-completion/bash_completion
fi

[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

PATH=$(python $HOME/.dotfiles/prompt-scripts/initialize_paths.py)
export PATH
launchctl setenv PATH $PATH

# Autocorrect typos in path names when using `cd`
shopt -s cdspell
shopt -s dirspell

# Just type directory without the cd
shopt -s autocd

shopt -s histappend
shopt -s checkwinsize

# Show some colors ls
export CLICOLOR=1
export LSCOLORS=cxfxcxdxbxegedabagacad
export GOPATH=~/.go/
export HISTSIZE=5000000
