for file in ~/.{path,bash_prompt,exports,aliases,functions,extra,hosts}; do
    if [[ -r "$file" ]]; then
        source "$file"
    fi
done
unset file

# yup I don't like vim
export EDITOR=pico

# /usr/local/bin before /usr/bin
PATH=/usr/local/bin:/usr/local/share/npm/bin:$(path_remove /usr/local/bin)
export PATH

if [[ -f $(brew --prefix)/bin/rbenv ]]; then
    eval "$(rbenv init -)"
    export RBENV_ROOT=/usr/local/opt/rbenv
fi

export NODE_PATH="/usr/local/lib/node"

if [[ -f $(brew --prefix)/share/bash-completion/bash_completion ]]; then
    . $(brew --prefix)/share/bash-completion/bash_completion
fi

# Autocorrect typos in path names when using `cd`
shopt -s cdspell
shopt -s dirspell

# Just type directory without the cd
shopt -s autocd

shopt -s histappend
shopt -s checkwinsize

# Show some colors ls
export CLICOLOR=1
export LSCOLORS=cxfxcxdxbxegedabagacad