#!/bin/bash

function _bash_prompt_get_git_state() {
    local GIT_STATE=""
    if [[ -n "$(git symbolic-ref HEAD 2>/dev/null)" ]]; then
        if [[ -n $(git status -s 2>/dev/null |grep -v ^# |grep -v "working directory clean") ]]; then
            GIT_STATE="$(tput setaf 1)✗"
        else
            GIT_STATE="$(tput setaf 2)✓"
        fi

        local GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)

        GIT_STATE+="[git:${GIT_BRANCH}]$(tput sgr0)"
    fi

    echo -e " ${GIT_STATE}"
}

function _bash_prompt_get_user_color() {
    local user_color=$(tput setaf 6)

    if [[ `whoami` == "root" ]]; then
        user_color=$(tput setaf 1)
    elif [[ `whoami` != "root" && `uname` == "Linux" ]]; then
        user_color=$(tput setaf 3)
    fi

    echo -e ${user_color}
}

function _bash_prompt_get_virtualenv() {
    local VIRTUALENV_PROMPT=""

    if [[ -n $VIRTUAL_ENV ]]; then
        VIRTUALENV_PROMPT="$(tput setab 5)[venv:$(echo ${VIRTUAL_ENV} | sed "s|${HOME}|~|")]$(tput sgr0)"
    fi

    echo -e ${VIRTUALENV_PROMPT}
}

function _bash_prompt_get_host_user_path() {
    local CWD=$(echo $(pwd) | sed "s|${HOME}|~|")
    local HOSTNAME=$(hostname)
    local USERNAME=$(whoami)

    local USER_COLOR=$(_bash_prompt_get_user_color)

    echo -e "${USER_COLOR}[👻 ${USERNAME}]$(tput sgr0) ${HOSTNAME} in $(tput setaf 6)${CWD}$(tput sgr0)"
}

function _bash_prompt_command() {
    local COLUMNS=$(tput cols)

    local PROMPT=$(_bash_prompt_get_host_user_path)
    local PROMPT_SIZE=$(echo -e ${PROMPT} | perl -pe 's/\e\[?.*?[\@-~]//g' | awk ' { print length } ')

    local GIT_STATE=$(_bash_prompt_get_git_state)
    local GIT_STATE_SIZE=$(echo -e ${GIT_STATE} | perl -pe 's/\e\[?.*?[\@-~]//g' | awk ' { print length } ')

    local VIRTUALENV_PROMPT=$(_bash_prompt_get_virtualenv)
    local VIRTUALENV_PROMPT_SIZE=$(echo ${VIRTUALENV_PROMPT} | perl -pe 's/\e\[?.*?[\@-~]//g' | awk ' { print length } ')

    local spacing_witdth
    ((spacing_witdth=${COLUMNS}-${GIT_STATE_SIZE}-${PROMPT_SIZE}-${VIRTUALENV_PROMPT_SIZE}))
    local SPACING=$(seq  -f " " -s '' ${spacing_witdth})

    PS1=${PROMPT}
    PS1+="${SPACING}"
    PS1+=${VIRTUALENV_PROMPT}${GIT_STATE}
    PS1+="\n→ "
}

PROMPT_COMMAND=_bash_prompt_command
